### ISSUE TITLE
[Open tasks] Replace storyboards with code

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#15]
## **GOAL**
Replace all the storyboards with UIs created via code.

### _**For not having one really huge branch, this will be split up in issues on a screen basis!**_ 

If you are interested in working on some screen, please comment on any of the open subtasks listed below.

### Subtasks
- [x] `NewLanguageViewController` 
https://github.com/misteu/VocabularyTraining/issues/17
- [x] `HomeScreenViewController` 
https://github.com/misteu/VocabularyTraining/issues/20
- [x] `LanguageScreenViewController`
https://github.com/misteu/VocabularyTraining/issues/21
- [x] `AddNewWordViewController` 
https://github.com/misteu/VocabularyTraining/issues/22
- [x] (Final issue) Remove any `Main.storyboard` references from the project, update `AppDelegate`.

## **WHY**
Storyboards are slow to load in Xcode and they are harder to maintain compared to plain code.

## **AC**
- There should not be any storyboards in the app.

- **Optional**
   First choice would be UIKit. It might make sense to also have a look whether it might make sense to start rewriting screens using SwiftUI. However, this will be way more work as it's a rewrite of everything.

**Comment by InsanelyHarsh** [comment]
Hi @misteu, I would like to work on this issue.

**Comment by misteu** [comment]
> Hi @misteu, I would like to work on this issue.

Hi @InsanelyHarsh!
Thank you for your interest in the project :)

Please tell me which screen you want to translate into code. I will create an issue and assign it to you.

Have a great weekend!

**Comment by InsanelyHarsh** [comment]
I think i will start with Add new Language View

**Comment by InsanelyHarsh** [comment]
Assign me, I have replaced NewLanguageViewController with Code!

**Comment by misteu** [comment]
> Assign me, I have replaced NewLanguageViewController with Code!

Hi there and thank you!
I created this issue for the specific View Controller you worked on:
https://github.com/misteu/VocabularyTraining/issues/17 (I think you need to comment there so that I can assign it to you)

**Comment by Kanishka3** [comment]
I am taking up the `HomeScreenViewController`.

**Comment by misteu** [comment]
Hi @Kanishka3 !
thanks for your interest! :) 

Can you comment inside of the issue for this screen? I will assign it to you then.

Actually, it is already assigned to somebody else but I don't think there wasn't any work done yet. 

Please comment there and maybe let's wait until tomorrow if he reacts.

**Comment by Kanishka3** [comment]
> Hi @Kanishka3 ! thanks for your interest! :)
> 
> Can you comment inside of the issue for this screen (#20)? I will assign it to you then.
> 
> Actually, it is already assigned to somebody else but I don't think there wasn't any work done yet.
> 
> Please comment there and maybe let's wait until tomorrow if he reacts.

Alright. Replies there. I am almost halfway done with the task.

**Comment by misteu** [comment]
all done!

**Comment by misteu** [comment]
all done!
