### ISSUE TITLE
[Replace Storyboard] NewLanguageViewController 

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#17]
## **GOAL**
Move UI of `NewLanguageViewController` to code to get rid of its storyboard representation.

## **WHY**
Eventually all the storyboards should be replaced with view controllers.

## **ACCEPTANCE CRITERIA**
- Storyboard should be completely replaced by a subclass of `UIViewController`
- Storyboard should be removed from the project

**Comment by misteu** [comment]
@InsanelyHarsh this is the issue for your PR, thanks!

**Comment by InsanelyHarsh** [comment]
Hi @misteu, I made PR can you review and merge it?

**Comment by misteu** [comment]
> Hi @misteu, I made PR can you review and merge it?

Hi, please see my comment in your PR

**Comment by misteu** [comment]
Thank you for contributing! Merged your PR: https://github.com/misteu/VocabularyTraining/pull/16
