### ISSUE TITLE
[Open Task] Replace storyboard for `HomeScreenViewController` with code. beginners-welcome 

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#20]
## **GOAL**
`HomeScreenViewController`'s storyboard reference should be replaced with code. The view controller should be instantiated without the need of a storyboard.

## **WHY**
Storyboards are hard to maintain.

## **ACCEPTANCE CRITERIA**

- Replace storyboard related stuff of `HomeScreenViewController` with code.
- Remove associated scene in `Main.storyboard`

**Comment by yogesh-9999** [comment]
Hey @misteu  assign me this issue

**Comment by misteu** [comment]
alright, I assigned you to the issue

**Comment by misteu** [comment]
Hello @yogesh-9999 !
How is it going? Do you have any open questions?

**Comment by shantanuSakpal** [comment]
hello @misteu , can you assign me this issue if its not solved?

**Comment by misteu** [comment]
> hello @misteu , can you assign me this issue if its not solved?

Hi @shantanuSakpal
Thanks for your interest on this issue!
Sure, feel free to work on this, assigned it to you :)

If you have any questions, please don't hesitate to ask.

**Comment by misteu** [comment]
Hey @yogesh-9999 I just un-assigned you as you did not share any progress and somebody else wants to work on it.

**Comment by misteu** [comment]
Hey @shantanuSakpal !
Are you still working on the issue? Please give a short update if you are or if you are having any problems with it.

Otherwise I would like to assign the issue to someone else.

**Comment by Kanishka3** [comment]
I am taking up this task.

**Comment by misteu** [comment]
Alright! I assigned it to you @Kanishka3 :)

Feel free to ask any questions if there is anything unclear.

As I wrote somewhere else, we are planning to do a redesign of the whole app. So it might make sense to not refactor too much in this view controller (as a lot of code will be touched/updated later anyway)

**Comment by Kanishka3** [comment]
@misteu Got it.

**Comment by misteu** [comment]
Hey @Kanishka3 

I assigned myself to the task as it looks like you were not working on it anymore. I want to finish up that last part of removing Storyboards now.

If you are still interested in contributing, we will implement some new designs soon (see readme).
