### ISSUE TITLE
[Open Task] Replace storyboard for `LanguageScreenViewController` with code.

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#21]
## **GOAL**
`LanguageViewController`'s storyboard reference should be replaced with code. The view controller should be instantiated without the need of a storyboard.

## **WHY**
Storyboards are hard to maintain.

## **ACCEPTANCE CRITERIA**

- Replace storyboard related stuff of `LanguageViewController` with code.
- Remove associated scene in `Main.storyboard`

**Comment by IceCurrent** [comment]
@misteu I want to work on it. Please assign me this issue

**Comment by K4stor** [comment]
Lemme work on it pls

**Comment by PranjalDev** [comment]
Hello, I picked up that task. can you assignee it to me?

**Comment by PranjalDev** [comment]
Created an PR for this: https://github.com/misteu/VocabularyTraining/pull/27

**Comment by misteu** [comment]
Thank you looks great so far!

I left a small comment there, I will quickly merge after you updated that.
