### ISSUE TITLE
[Open Task] Replace storyboard for `AddNewWordViewController` with code.

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#22]
## **GOAL**
`AddNewWordViewController`'s storyboard reference should be replaced with code. The view controller should be instantiated without the need of a storyboard.

## **WHY**
Storyboards are hard to maintain.

## **ACCEPTANCE CRITERIA**

- Replace storyboard related stuff of `AddNewWordViewController` with code.
- Remove associated scene in `Main.storyboard`

**Comment by K4stor** [comment]
Lemme work on it pls

**Comment by nayushi** [comment]
Hello, I'm working on that. Can you assignee that task for me? :)

**Comment by misteu** [comment]
> Hello, I'm working on that. Can you assignee that task for me? :)

Hey @nayushi !
thanks for helping out 😃 
I just assigned that issue to you.

Feel free to ask, if you have any questions 👍

Have fun and thanks again!

**Comment by nayushi** [comment]
@misteu I'm receiving a 403 to push the refactor branch :(
