### ISSUE TITLE
[Refactor] Simple Coordinator pattern

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#24]
## **GOAL**
`UINavigationController` should be used for hosting all the view controllers and managing navigation.
Where it makes sense, presenting/dismissing might be replaced with pushing/popping on a navigation stack.

Besides that it makes sense to implement a simple coordinator pattern as @PranjalDev mentioned.

## **WHY**
Currently there are back buttons implemented as `UIBarButtonItem` look-a-likes. This adds a lot of unnecessary code and makes it easy to miss something whenever there is a change.

## **ACCEPTANCE CRITERIA**
- Have an actual navigation bar
- Have a simple/lightweight coordinator pattern implemented

**Comment by PranjalDev** [comment]
I would love to pick this up,

Also,
As we are talking about navigation here, we could also introduce light weight coordinator pattern to handle the navigation and the dependency injection between the view controllers, 

Let me know if you are open for that coordinator change, if not will move forward with the MainNavigtor with enum approach

**Comment by misteu** [comment]
Hey!

actually this is a great idea! Having a lightweight coordinator pattern here would be really nice.

Would be happy if you want to work on this 👍

Not sure though if we should already start with it or rather wait for all of the storyboard screens being pure code.

I will already update the issue a little bit and assign it to you.

**Comment by PranjalDev** [comment]
What we could do is develop this in phased manner like

 - Implementing main coordinator, and adding the home view controller and navigation going through that in this phase
 - Create separate issues for coordinators required for view controllers once they are migrated to code

**Comment by PranjalDev** [comment]
Hey @misteu
One of my peer wanted to contribute to this project, specifically to this part, and he already have a PR ready, 
He would be replying to this, Issue thread, Can you assign it to him?

**Comment by misteu** [comment]
sure! I assigned you @NukeNalin
