### ISSUE TITLE
[Localization] Brazilian portuguese

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#31]
## **GOAL**
The app's strings should be translated to brazilian portuguese.

## **WHY**
@nayushi offered to add localization for brazilian portuguese

## **ACCEPTANCE CRITERIA**

- All NSLocalizedStrings should be translated
- If possible, the privacy policy html should be translated as well. However, for this rather large document I think it's fine to use deepl.com and quickly read through it afterwards to fix the largest issues.

**Comment by misteu** [comment]
Thank you for your work again!

**Comment by Kanishka3** [comment]
I can look into localising it in Hindi. You can assign it to me
