### ISSUE TITLE
[Bugfix] Fix clipped input field on small devices

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#35]
## **GOAL**
Input should not be clipped on smaller devices.

## **WHY**
I just saw that this input is clipped on an iPod touch 7th Gen simulator. Maybe it's clipped on other smaller devices as well.

![grafik](https://user-images.githubusercontent.com/35889530/198306308-24cf4fda-ebaf-4c29-b4f1-6fc820c884cf.png)

It should have some margin of 8 or 16 (whatever looks better/more consistent) to leading and trailing edges.

## **ACCEPTANCE CRITERIA**
What needs to be done so that this task has the accepted changes?

- input should not be clipped anymore

**Comment by DominatorVbN** [comment]
Can you assign this to me picking this up

**Comment by DominatorVbN** [comment]
Created the PR at: https://github.com/misteu/VocabularyTraining/pull/36
