### ISSUE TITLE
[Redesign] New App design + A11y definition

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#39]
## **GOAL**
App should get a redesign.
This issue/task is only about the redesign itself.

There will be follow-up tasks for the different screens.

For icons I would say to keep it simple an use SFSymbols if there isn't needed something special.

Optionally:
- redesign App icon

## **WHY**
To make the app look cleaner and make it accessible.

## **ACCEPTANCE CRITERIA**
What needs to be done so that this task has the accepted changes?

- Have screens designed in Figma. The link to the figma file could be placed in some folder that makes sense or even just under a new section in the readme.
- Have Accessibility defined
  - accessibilityLabels, -traits and -values where needed
  - definition of VoiceOver order if changes need to be applied
  - definition of UIAccessibilityNotifications (if they are needed somewhere)

**Comment by nayushi** [comment]
Hey @misteu, assignee that for me :)
