### ISSUE TITLE
[Improvement] Prevent accidentally doubled words/phrases/dictionaries

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#5]
## **GOAL**
Have something in place that prevents accidentally doubled words/phrases/languages.

## **WHY**
You might accidentally add an already existing word/phrase to you list if you did not know it's already in there.

## **ACCEPTANCE CRITERIA**
What needs to be done so that this task has the accepted changes?

- check when creating new dictionaries + new words
- check a new entry against existing entries in a case insensitive manner, i.e. if `cat` already exists, the logic should match `cat`, `CAT` and `Cat`, etc. (<- we could also only match case sensitive if you think this does make more sense )
- Show an alert to the user with "Cancel" and "Add Anyway" buttons.

**Comment by Kanishka3** [comment]
Can you add more detail to this issue? Are we looking for autocomplete or the possibility not to add existing words?
@misteu

**Comment by misteu** [comment]
Hey,
sorry for my late reply and thanks for asking!

Right, I didn't describe that quite right. I thought something similar to seeing your browser history when typing in a new word. So that you can instantly see if you already have the same or something similar in your list of words.

I mean as you could basically type in whole sentences in your dictionary, it might be the case that you already had added a similar one some weeks/month ago that you do not remember.

However, maybe that is still a little unclear how exactly it would look. Also regarding the upcoming redesign we might touch it again anyway.

Maybe let's start with a simple (case insensitive) check against existing words + an "add anyway" button somewher, I'll update the issue a little bit.

Let me know what you think :)

**Comment by misteu** [comment]
@Kanishka3 Alright, I updated it a little bit from the first rough idea that I described in there before.

**Comment by Kanishka3** [comment]
@misteu Got it. Added the exact logic as the description with that alert to the app :) 

Feel free to checkout and merge [this PR](https://github.com/misteu/VocabularyTraining/pull/41).

**Comment by misteu** [comment]
Hi @Kanishka3 
Thank you for your contribution! :) I left some minor comments on your PR. Let me know if you need any help or an additional review.
