### ISSUE TITLE
Improve screen for newly added languages (that do not have words yet)

### ISSUE THREAD

**Issue by misteu** [misteu/VocabularyTraining#7]
Currently it looks like that when a new language was created:
<img width="300" alt="grafik" src="https://user-images.githubusercontent.com/35889530/137951572-7f329d7a-7c6f-4b6d-a3a3-ebd00f83f493.png">

This screen does not look right with all these useless sorting buttons. There was an information text some releases ago but I might have accidentally removed it when adding the buttons.

It would be nicer to hide the sorting buttons and the info button when there is no data and have some information there instead, similar to the empty home screen
<img width="250" alt="grafik" src="https://user-images.githubusercontent.com/35889530/137951811-9b592c13-a179-40ba-8b54-82e081c7dedc.png">

If the localized string is still somewhere you could just use that or create a new one.

**Comment by misteu** [comment]
Hey, this one is still open :) Nobody started working on it yet.

It should be a fairly simple fix should be really good for newcomers, please let me know if you need any help :)

**Comment by K4stor** [comment]
Sorry I totally missed your answer !

I will work on it next week during the next Hacktober :-D

**Comment by misteu** [comment]
Thanks for your reply! Please let me know when you started, I'll quickly assign it to you then again :)

Have a nice weekend!

**Comment by misteu** [comment]
Hi again,
sorry, I also seem to have completely missed that you did some changes already a year ago :D here https://github.com/misteu/VocabularyTraining/pull/9

Can you change rebase this (as I merged something else before) and make only the changes needed? I saw that there are a lot of changes in the view controller file.

**Comment by K4stor** [comment]
lol I totaly forgot too :-D sure, but I wont make it until tomorrow

**Comment by misteu** [comment]
> lol I totaly forgot too :-D sure, but I wont make it until tomorrow 

haha, no pressure 😀 
As I said, did not see it until now, so feel free to work on it whenever you have some time :)

**Comment by K4stor** [comment]
Ok I updated the PR should be good now
